### PR TITLE
all: port to Plan 9

### PR DESCRIPTION
**Pull request by fhs**
Depends on PR #26 for consistent behavior of ReadAt.

Helps rjkroege/edwood#115

### CODE REVIEW

**Comment by ddevault** [comment]
Tested this on 9front, worked great after fixing the conflicts.

**Comment by fhs** [comment]
@ddevault Thanks for testing. I've rebased.

**Comment by ddevault** [comment]
Thanks! I'm working on another patch which will add a factotum module as well.

**Comment by fhs** [comment]
@ddevault I worked on a factotum package a long time ago: [bitbucket.org/fhs/go-plan9-auth/auth](https://godoc.org/bitbucket.org/fhs/go-plan9-auth/auth). It hasn't gotten much use over the years. Feel free to make use of it (if it's useful).

I should probably move the package from mercurial to git/github, since mercurial is going away in bitbucket. But then I'd rather have a factotum package inside `9fans.net/go/...`.

**Comment by ddevault** [comment]
Excellent! I'll pull it into 9fans/go. And if you're looking for a new Mercurial host, [my own services are available](https://sourcehut.org/blog/2019-08-21-sourcehut-welcomes-bitbucket-refugees/).

**Comment by floren** [comment]
Registering a +1 in that this would be really useful for me.

**Comment by nvkv** [comment]
Is there any chance to get this merged? It would be really useful.

**Comment by rsc** [comment]
Apologies, but at least in this form, a port to Plan 9 is out of scope for this package. In particular I hope to kill off the entire devdraw RPC usage entirely, instead connecting directly to the host graphics and generally simplifying programs built against this API. That would invalidate much of the code being added to draw here, since the "draw protocol" will not exist anymore.

The situation for plan9.Client is similarly awkward: it seems wrong to have a mode where that code falls back to file system access.

I'm willing to make small Plan 9-related changes, but I don't want to have to maintain wholly separate implementations of the libraries just for Plan 9.

For now it seems best to maintain a fork of this package for use on Plan 9. Again, sorry. I appreciate the sad irony.

**Comment by rsc** [comment]
@fhs and I have been working to move github.com/fhs/acme-lsp to 9fans.net/acme-lsp, hosted in https://github.com/9fans/acme-lsp, and as part of that I have merged fhs/9fans-go's plan9 branch into the main 9fans.net/go branch. The fork should no longer be necessary.

**Pull request closed without merging**
